id: I579977BB
legacy_id: P001714
ocr_import_info:
  bdrc_scan_id: W1GS54860
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T10:43:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T20:05:28.223748+00:00'
last_modified: 2022-08-31 04:05:40.238770
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1GS54860
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1GS54860
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐུབ་དབང་གནས་བརྟན་བཅུ་དྲུག་དང་བཅས་པ་ལ་མཆོད་ཅིང་གསོལ་བ་གདབ་པའི་ཆོ་ག་ཐུབ་བསྟན་རྒྱས་བྱེད་ཡིད་བཞིན་ནོར་བུའི་སྤྱི་དངོས་རྗེས་གསུམ་དུ་ཇི་ལྟར་བྱ་བའི་ཚུལ་གསལ་བར་བཀོད་པ་དངོས་གྲུབ་ཀུན་འབྱུང་།
  author: རྟ་ཚག ༠༩་ངག་དབང་བློ་བཟང་བསྟན་པའི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.659850547263848
  ocr_word_median_confidence_index: 0.7400000095367432
quality: null
bases:
  I1GS54862:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS54862
      total_pages: 82
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS54862.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.659850547263848
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
