id: I579977BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:43:20+00:00'
last_modified: '2022-06-07T14:53:33.686436+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS54860
  title: ཐུབ་དབང་གནས་བརྟན་བཅུ་དྲུག་དང་བཅས་པ་ལ་མཆོད་ཅིང་གསོལ་བ་གདབ་པའི་ཆོ་ག་ཐུབ་བསྟན་རྒྱས་བྱེད་ཡིད་བཞིན་ནོར་བུའི་སྤྱི་དངོས་རྗེས་གསུམ་དུ་ཇི་ལྟར་བྱ་བའི་ཚུལ་གསལ་བར་བཀོད་པ་དངོས་གྲུབ་ཀུན་འབྱུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    64A6:
      image_group_id: I1GS54862
      title: ''
      total_pages: 82
      order: 1
      base_file: 64A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
